# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_actions', '0002_auto_20180708_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('selected', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('application_date',),
            },
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('salary', models.PositiveIntegerField(max_length=9, unique=True)),
                ('weekly_workload', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user_actions.Enterprise')),
            ],
            options={
                'verbose_name': 'job_opportunity',
                'verbose_name_plural': 'job_opportunities',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job_opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_opportunity', to='jobs.JobOpportunity'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='user_actions.Student'),
        ),
    ]
