# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='salary',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
