# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180709_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='enterprise_id',
            new_name='enterprise',
        ),
    ]
