# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pw', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('validation_pending', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'enterprise',
                'verbose_name_plural': 'enterprises',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pw', models.CharField(max_length=200)),
                ('id_doc_number', models.PositiveIntegerField(max_length=9, unique=True)),
                ('enroll_number', models.PositiveIntegerField(unique=True)),
                ('major_id', models.PositiveIntegerField(db_index=True)),
                ('qualifications', models.TextField(blank=True)),
                ('gpa', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('validation_pending', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('time_available_start', models.TextField()),
                ('time_available_end', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ('name',),
            },
        ),
    ]
