# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_doc_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
