# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0002_auto_20180708_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='able',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='able',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='validation_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='validation_pending',
            field=models.BooleanField(default=True),
        ),
    ]
