# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0003_auto_20180712_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
